import { Product, Supplier, Customer, PurchaseOrder, Sale, AuditLog, ScanHistoryItem, CompanySettings, UserProfile, SystemNotification } from './types';

export const INITIAL_COMPANY_SETTINGS: CompanySettings = {
  companyName: 'Stoq.',
  logoUrl: 'https://picsum.photos/seed/stoq/200/200',
  taxNumber: '27AABCU9603R1ZM',
  defaultTaxRate: 18.0,
  currencySymbol: '₹',
  currencyCode: 'INR',
  address: 'Cyber City, DLF Phase 2, Gurugram, Haryana 122002',
  phone: '+91 (124) 490-8800',
  email: 'ops@stoq.io',
  lowStockEmailAlerts: true,
  autoReorderSuggestions: true,
  themeMode: 'dark',
};

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr_001',
  name: 'Panshul',
  email: 'panshul@stoq.io',
  role: 'OWNER',
  companyName: 'Stoq.',
  avatarUrl: '/avatars/panshul.svg',
};

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_101',
    name: 'TechCore Bharat Logistics',
    contactPerson: 'Rajesh Sharma',
    email: 'sales@techcore-bharat.in',
    phone: '+91 (11) 4567-8901',
    address: 'Plot 42, Okhla Industrial Area Phase III, New Delhi 110020',
    categories: ['Electronics', 'Gadgets'],
    reliabilityRating: 4.8,
    leadTimeDays: 3,
    totalOrders: 42,
  },
  {
    id: 'sup_102',
    name: 'Chikmagalur Artisan Roast Co.',
    contactPerson: 'Ananya Rao',
    email: 'orders@chikmagalur-roast.in',
    phone: '+91 (80) 2234-5678',
    address: 'Estate 14, MG Road, Indiranagar, Bengaluru, KA 560038',
    categories: ['Beverages', 'Gourmet'],
    reliabilityRating: 4.9,
    leadTimeDays: 2,
    totalOrders: 68,
  },
  {
    id: 'sup_103',
    name: 'Vardhman Textiles & Apparel',
    contactPerson: 'Arjun Mehta',
    email: 'b2b@vardhmantextiles.in',
    phone: '+91 (22) 2890-1234',
    address: 'Unit 8, Lower Parel Industrial Estate, Mumbai, MH 400013',
    categories: ['Apparel', 'Accessories'],
    reliabilityRating: 4.6,
    leadTimeDays: 5,
    totalOrders: 29,
  },
  {
    id: 'sup_104',
    name: 'Bharat PowerTools & Hardware',
    contactPerson: 'Vikramaditya Singhania',
    email: 'supply@bharattools.in',
    phone: '+91 (44) 2498-7654',
    address: 'Sector 5, Guindy Industrial Estate, Chennai, TN 600032',
    categories: ['Tools', 'Hardware'],
    reliabilityRating: 4.7,
    leadTimeDays: 4,
    totalOrders: 35,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_201',
    name: 'Pooja Iyer',
    companyName: 'Kaapi Nirvana Cafes',
    email: 'pooja@kaapinirvana.com',
    phone: '+91 98450 12345',
    address: '74 Commercial Street, Tasker Town, Bengaluru, KA 560001',
    totalOrders: 18,
    totalSpent: 4850.00,
    lastOrderDate: '2026-07-24',
  },
  {
    id: 'cust_202',
    name: 'Rohan Deshmukh',
    companyName: 'Zenith Coworking Hubs',
    email: 'rohan@zenithwork.in',
    phone: '+91 98201 98765',
    address: 'Bandra-Kurla Complex, Bandra East, Mumbai, MH 400051',
    totalOrders: 12,
    totalSpent: 9240.50,
    lastOrderDate: '2026-07-25',
  },
  {
    id: 'cust_203',
    name: 'Meera Nambiar',
    companyName: 'Nambiar Lifestyle Retail',
    email: 'meera@nambiar-retail.in',
    phone: '+91 94470 54321',
    address: 'Panampilly Nagar, Kochi, KL 682036',
    totalOrders: 24,
    totalSpent: 14320.00,
    lastOrderDate: '2026-07-26',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: 'Wireless Ergonomic Mechanical Keyboard',
    sku: 'KB-WIR-001',
    barcode: '8901234567891',
    barcodeFormat: 'EAN13',
    category: 'Electronics',
    supplierId: 'sup_101',
    supplierName: 'TechCore Bharat Logistics',
    purchasePrice: 45.00,
    sellingPrice: 89.99,
    quantity: 68,
    minReorderLevel: 20,
    maxStockLevel: 150,
    stockStatus: 'IN_STOCK',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&auto=format&fit=crop&q=80',
    location: 'Aisle 3, Shelf B2',
    unit: 'pcs',
    createdAt: '2026-01-15',
    updatedAt: '2026-07-26',
    description: 'Hot-swappable tactile RGB mechanical keyboard with Bluetooth 5.2 and USB-C.',
  },
  {
    id: 'prod_002',
    name: 'Precision Optical USB-C Mouse',
    sku: 'MS-OPT-002',
    barcode: '012345678905',
    barcodeFormat: 'UPC',
    category: 'Electronics',
    supplierId: 'sup_101',
    supplierName: 'TechCore Bharat Logistics',
    purchasePrice: 18.50,
    sellingPrice: 39.99,
    quantity: 14,
    minReorderLevel: 25,
    maxStockLevel: 100,
    stockStatus: 'LOW_STOCK',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&auto=format&fit=crop&q=80',
    location: 'Aisle 3, Shelf B3',
    unit: 'pcs',
    createdAt: '2026-01-20',
    updatedAt: '2026-07-27',
    description: 'High precision 16000 DPI gaming optical sensor mouse with ultra-light cable.',
  },
  {
    id: 'prod_003',
    name: 'Coorg Single-Estate Coffee Beans (1kg)',
    sku: 'BEA-CRG-003',
    barcode: '7890123456784',
    barcodeFormat: 'EAN13',
    category: 'Beverages',
    supplierId: 'sup_102',
    supplierName: 'Chikmagalur Artisan Roast Co.',
    purchasePrice: 12.00,
    sellingPrice: 24.50,
    quantity: 85,
    minReorderLevel: 15,
    maxStockLevel: 120,
    stockStatus: 'IN_STOCK',
    expiryDate: '2026-11-30',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&auto=format&fit=crop&q=80',
    location: 'Aisle 1, Shelf A1',
    unit: 'kg',
    createdAt: '2026-02-10',
    updatedAt: '2026-07-25',
    description: 'Single-origin shade-grown Coorg Arabica beans with roasted hazelnut notes.',
  },
  {
    id: 'prod_004',
    name: 'Monsooned Malabar Premium Dark Roast (1kg)',
    sku: 'BEA-MAL-004',
    barcode: '5432109876543',
    barcodeFormat: 'EAN13',
    category: 'Beverages',
    supplierId: 'sup_102',
    supplierName: 'Chikmagalur Artisan Roast Co.',
    purchasePrice: 11.50,
    sellingPrice: 22.99,
    quantity: 6,
    minReorderLevel: 20,
    maxStockLevel: 100,
    stockStatus: 'LOW_STOCK',
    expiryDate: '2026-08-15',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    location: 'Aisle 1, Shelf A2',
    unit: 'kg',
    createdAt: '2026-02-12',
    updatedAt: '2026-07-27',
    description: 'Aromatic monsooned Malabar beans with smooth chocolate finish and spicy fragrance.',
  },
  {
    id: 'prod_005',
    name: 'Kashmiri Pashmina Heavyweight Hoodie',
    sku: 'APP-HOO-005',
    barcode: '4567890123456',
    barcodeFormat: 'CODE128',
    category: 'Apparel',
    supplierId: 'sup_103',
    supplierName: 'Vardhman Textiles & Apparel',
    purchasePrice: 38.00,
    sellingPrice: 85.00,
    quantity: 0,
    minReorderLevel: 10,
    maxStockLevel: 60,
    stockStatus: 'OUT_OF_STOCK',
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&auto=format&fit=crop&q=80',
    location: 'Rack C, Bin 4',
    unit: 'pcs',
    createdAt: '2026-03-01',
    updatedAt: '2026-07-26',
    description: 'Fine blended wool thermal insulation zip hoodie in carbon slate.',
  },
  {
    id: 'prod_006',
    name: 'Heavy Duty Cordless Power Drill 20V',
    sku: 'TL-DRL-006',
    barcode: '9876543210123',
    barcodeFormat: 'EAN13',
    category: 'Tools',
    supplierId: 'sup_104',
    supplierName: 'Bharat PowerTools & Hardware',
    purchasePrice: 62.00,
    sellingPrice: 129.99,
    quantity: 42,
    minReorderLevel: 12,
    maxStockLevel: 80,
    stockStatus: 'IN_STOCK',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&auto=format&fit=crop&q=80',
    location: 'Warehouse B, Bay 1',
    unit: 'set',
    createdAt: '2026-03-15',
    updatedAt: '2026-07-22',
    description: '20V brushless motor drill driver kit with 2x 4.0Ah Lithium-ion batteries.',
  },
  {
    id: 'prod_007',
    name: 'Ultra Wide 34-inch Curved Studio Monitor',
    sku: 'MON-34-007',
    barcode: '1234567890128',
    barcodeFormat: 'EAN13',
    category: 'Electronics',
    supplierId: 'sup_101',
    supplierName: 'TechCore Bharat Logistics',
    purchasePrice: 280.00,
    sellingPrice: 499.00,
    quantity: 19,
    minReorderLevel: 8,
    maxStockLevel: 40,
    stockStatus: 'IN_STOCK',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=80',
    location: 'Aisle 4, Top Shelf',
    unit: 'pcs',
    createdAt: '2026-04-01',
    updatedAt: '2026-07-24',
    description: '34-inch WQHD 144Hz IPS curved monitor with 99% sRGB coverage and 65W USB-C PD.',
  },
  {
    id: 'prod_008',
    name: 'Recycled Bamboo A5 Notebook set (Pack of 3)',
    sku: 'STA-NOT-008',
    barcode: 'QR-NOT-008-APEX',
    barcodeFormat: 'QR',
    category: 'Office',
    supplierId: 'sup_103',
    supplierName: 'Vardhman Textiles & Apparel',
    purchasePrice: 4.50,
    sellingPrice: 12.99,
    quantity: 195,
    minReorderLevel: 30,
    maxStockLevel: 150,
    stockStatus: 'OVERSTOCKED',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80',
    location: 'Aisle 2, Bin C1',
    unit: 'pack',
    createdAt: '2026-04-10',
    updatedAt: '2026-07-20',
    description: 'Eco-friendly dotted bamboo grid journal notebooks for daily planning.',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_501',
    poNumber: 'PO-2026-089',
    supplierId: 'sup_101',
    supplierName: 'TechCore Bharat Logistics',
    items: [
      {
        productId: 'prod_002',
        productName: 'Precision Optical USB-C Mouse',
        sku: 'MS-OPT-002',
        quantity: 50,
        unitCost: 18.50,
        totalCost: 925.00,
      },
    ],
    subtotal: 925.00,
    tax: 78.63,
    total: 1003.63,
    status: 'SENT',
    issueDate: '2026-07-25',
    expectedDeliveryDate: '2026-07-29',
    notes: 'Urgent restocking due to low inventory level alert.',
  },
  {
    id: 'po_502',
    poNumber: 'PO-2026-088',
    supplierId: 'sup_102',
    supplierName: 'Chikmagalur Artisan Roast Co.',
    items: [
      {
        productId: 'prod_004',
        productName: 'Monsooned Malabar Premium Dark Roast (1kg)',
        sku: 'BEA-MAL-004',
        quantity: 40,
        unitCost: 11.50,
        totalCost: 460.00,
      },
      {
        productId: 'prod_003',
        productName: 'Coorg Single-Estate Coffee Beans (1kg)',
        sku: 'BEA-CRG-003',
        quantity: 30,
        unitCost: 12.00,
        totalCost: 360.00,
      },
    ],
    subtotal: 820.00,
    tax: 69.70,
    total: 889.70,
    status: 'RECEIVED',
    issueDate: '2026-07-18',
    expectedDeliveryDate: '2026-07-20',
    receivedDate: '2026-07-20',
    notes: 'Regular bi-weekly coffee bean shipment.',
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale_701',
    invoiceNumber: 'INV-2026-3401',
    customerId: 'cust_201',
    customerName: 'Kaapi Nirvana Cafes',
    items: [
      {
        productId: 'prod_003',
        productName: 'Coorg Single-Estate Coffee Beans (1kg)',
        sku: 'BEA-CRG-003',
        quantity: 10,
        unitPrice: 24.50,
        totalPrice: 245.00,
      },
    ],
    subtotal: 245.00,
    tax: 20.83,
    totalAmount: 265.83,
    profit: 125.00,
    paymentStatus: 'PAID',
    paymentMethod: 'STRIPE',
    saleDate: '2026-07-27',
  },
  {
    id: 'sale_702',
    invoiceNumber: 'INV-2026-3400',
    customerId: 'cust_202',
    customerName: 'Zenith Coworking Hubs',
    items: [
      {
        productId: 'prod_001',
        productName: 'Wireless Ergonomic Mechanical Keyboard',
        sku: 'KB-WIR-001',
        quantity: 4,
        unitPrice: 89.99,
        totalPrice: 359.96,
      },
      {
        productId: 'prod_002',
        productName: 'Precision Optical USB-C Mouse',
        sku: 'MS-OPT-002',
        quantity: 4,
        unitPrice: 39.99,
        totalPrice: 159.96,
      },
    ],
    subtotal: 519.92,
    tax: 44.19,
    totalAmount: 564.11,
    profit: 266.00,
    paymentStatus: 'PAID',
    paymentMethod: 'CREDIT_CARD',
    saleDate: '2026-07-26',
  },
  {
    id: 'sale_703',
    invoiceNumber: 'INV-2026-3399',
    customerId: 'cust_203',
    customerName: 'Nambiar Lifestyle Retail',
    items: [
      {
        productId: 'prod_005',
        productName: 'Kashmiri Pashmina Heavyweight Hoodie',
        sku: 'APP-HOO-005',
        quantity: 8,
        unitPrice: 85.00,
        totalPrice: 680.00,
      },
    ],
    subtotal: 680.00,
    tax: 57.80,
    totalAmount: 737.80,
    profit: 376.00,
    paymentStatus: 'PAID',
    paymentMethod: 'BANK_TRANSFER',
    saleDate: '2026-07-25',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_901',
    timestamp: '2026-07-27 10:14:22',
    productId: 'prod_003',
    productName: 'Ethiopian Yirgacheffe Coffee Beans (1kg)',
    type: 'STOCK_OUT',
    quantityChange: -10,
    previousQuantity: 95,
    newQuantity: 85,
    performedBy: 'Panshul',
    reason: 'Fulfill Sale INV-2026-3401',
    referenceId: 'sale_701',
  },
  {
    id: 'log_902',
    timestamp: '2026-07-26 15:30:10',
    productId: 'prod_002',
    productName: 'Precision Optical USB-C Mouse',
    type: 'STOCK_OUT',
    quantityChange: -4,
    previousQuantity: 18,
    newQuantity: 14,
    performedBy: 'Panshul',
    reason: 'Fulfill Sale INV-2026-3400',
    referenceId: 'sale_702',
  },
  {
    id: 'log_903',
    timestamp: '2026-07-20 09:00:00',
    productId: 'prod_004',
    productName: 'Organic Colombian Dark Roast (1kg)',
    type: 'STOCK_IN',
    quantityChange: 40,
    previousQuantity: 10,
    newQuantity: 50,
    performedBy: 'Panshul',
    reason: 'Received PO-2026-088',
    referenceId: 'po_502',
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif_01',
    title: 'Low Stock Alert',
    message: 'Organic Colombian Dark Roast (1kg) is at 6 units (Min reorder: 20).',
    timestamp: '10 minutes ago',
    type: 'LOW_STOCK',
    read: false,
  },
  {
    id: 'notif_02',
    title: 'Stock Out Alert',
    message: 'Merino Wool Heavyweight Hoodie is out of stock (0 units).',
    timestamp: '1 hour ago',
    type: 'OUT_OF_STOCK',
    read: false,
  },
  {
    id: 'notif_03',
    title: 'New Order Sale',
    message: 'Invoice INV-2026-3401 paid ($265.83) by Urban Coffee House.',
    timestamp: '2 hours ago',
    type: 'NEW_ORDER',
    read: true,
  },
];
